### ISSUE TITLE
attribute error

### ISSUE THREAD

**Issue by scalar27** [amanvirparhar/weebo#2]
Just trying this now on my M1 Max 64 Gb.  I get this error:

AttributeError: type object 'EspeakWrapper' has no attribute 'set_data_path'. Did you mean: 'data_path'?

thanks.

**Comment by dxcore35** [comment]
Same error

**Comment by scalar27** [comment]
I've had issues with espeak before...

**Comment by itzzdeep** [comment]
Comment the lines [45-46](https://github.com/amanvirparhar/weebo/blob/main/main.py#L45-L46) in `main.py`:
```python
espeak data_path = espeakng_loader.get_data_path()
espeak_ lib_ path = espeakng_loader.get_library_path)
# EspeakWrapper.set_data_path(espeak_data_path)
# EspeakWrapper.set library(espeak lib path)
```

**Comment by scalar27** [comment]
Thanks.  When I comment out the two lines it proceeds further until it tries to analyze my first input.  Then it crashes with:

Error processing file '/usr/share/espeak-ng-data/phontab': No such file or directory.

**Comment by McAvity** [comment]
I'm working on mac, Python 3.9.20 (other version throw errors during `pip install -r requirements.txt`)

### after commenting both lines
The problem persists, the app straight away throws the following error:
```
Traceback (most recent call last):
  File "/Users/marcin/.pyenv/versions/3.9.20/envs/weebo/lib/python3.9/site-packages/sounddevice.py", line 857, in callback_ptr
    return _wrap_callback(callback, data, frames, time, status)
  File "/Users/marcin/.pyenv/versions/3.9.20/envs/weebo/lib/python3.9/site-packages/sounddevice.py", line 2735, in _wrap_callback
    callback(*args)
  File "/Users/marcin/workspace/weebo/main.py", line 143, in callback
    self.create_and_play_response(text)
  File "/Users/marcin/workspace/weebo/main.py", line 218, in create_and_play_response
    ph = self.phonemize(chunk_text)
  File "/Users/marcin/workspace/weebo/main.py", line 76, in phonemize
    phonemes = phonemizer.phonemize(
  File "/Users/marcin/.pyenv/versions/3.9.20/envs/weebo/lib/python3.9/site-packages/phonemizer/phonemize.py", line 206, in phonemize
    phonemizer = BACKENDS[backend](
  File "/Users/marcin/.pyenv/versions/3.9.20/envs/weebo/lib/python3.9/site-packages/phonemizer/backend/espeak/espeak.py", line 45, in __init__
    super().__init__(
  File "/Users/marcin/.pyenv/versions/3.9.20/envs/weebo/lib/python3.9/site-packages/phonemizer/backend/espeak/base.py", line 39, in __init__
    super().__init__(
  File "/Users/marcin/.pyenv/versions/3.9.20/envs/weebo/lib/python3.9/site-packages/phonemizer/backend/base.py", line 77, in __init__
    raise RuntimeError(  # pragma: nocover
RuntimeError: espeak not installed on your system
```
But I do have espeak installed:
```
$ whereis espeak
espeak: /opt/homebrew/bin/espeak
```

The variables that are not set (because of commenting) are like the following:
```
Data path: /Users/marcin/.pyenv/versions/3.9.20/envs/weebo/lib/python3.9/site-packages/espeakng_loader/espeak-ng-data
Library path: /Users/marcin/.pyenv/versions/3.9.20/envs/weebo/lib/python3.9/site-packages/espeakng_loader/libespeak-ng.dylib
```

### after uncommenting EspeakWrapper.set_library(espeak_lib_path)
The application starts, it listens to my voice and produces the llm output, but the voice is not said. The error I get is:
```
Error processing file '/Users/runner/work/espeakng-loader/espeakng-loader/espeak-ng/_dynamic/share/espeak-ng-data/phontab': No such file or directory.
```

This folder obviously does not exist on my computer, because the actual data path is elsewhere (see above). It seems, there is a need to set the `espeak_data_path` variable, but I don't see a way to do it.

What version of `EspeakWrapper` are you using in your code (the version that has `set_data_path` implemented)?

**Comment by scalar27** [comment]
I am using python3.12, which seems to work fine.  

>  pip list | grep espeak
espeakng                  1.0.3
espeakng-loader           0.2.3

**Comment by michaelmj** [comment]
I found 2 different ways to get this working on macOS.

Replace lines 45 and 46 with:
```python
os.environ['PHONEMIZER_ESPEAK_DATA_PATH'] = espeakng_loader.get_data_path()
os.environ['PHONEMIZER_ESPEAK_LIBRARY'] = espeakng_loader.get_library_path()
``` 

OR

Use this fork and branch of phonemizer - https://github.com/thewh1teagle/phonemizer-fork/tree/feat/custom-espeak-data
Which was referenced from this PR - https://github.com/bootphon/phonemizer/pull/191

**Comment by scalar27** [comment]
Are either of these preferable to commenting out the two lines as suggested above?  (Which worked for me.) Does it not work for you?

**Comment by michaelmj** [comment]
Correct.
On macOS 15.2 with Python 3.12 just commenting those lines did not work for me. 
I still ended up with errors that espeak was not installed.

**Comment by amanvirparhar** [comment]
Oops, my bad! @michaelmj is right - I'm using this [fork](https://github.com/thewh1teagle/phonemizer-fork) of phonemizer, but I guess I didn't freeze the `requirements.txt` correctly.

I've [changed](https://github.com/amanvirparhar/weebo/blob/4423c7ea5e7609752e44460098a31d4df83faa89/requirements.txt#L47) that though, so please pull the changes, and let me know if the script works now! 🙂

**Comment by scalar27** [comment]
I can confirm things work well now, thanks!  I do run into problems when trying to use a larger model with ollama, even though that model runs fast stand alone without weebo.  Any suggestions of parameters to tweak?

**Comment by amanvirparhar** [comment]
> I can confirm things work well now, thanks! I do run into problems when trying to use a larger model with ollama, even though that model runs fast stand alone without weebo. Any suggestions of parameters to tweak?

If I had to wager a guess, I'd say that it's probably a memory issue. Weebo also loads Whisper Small and Kokoro-82M into memory (in addition to whatever language model you use), which might be why using a larger LLM leads to problems.

You might be able to get a better picture of what's happening under the hood by running `htop` (or some similar tool) concurrently.

**Comment by thewh1teagle** [comment]
I'm glad to see that finally people benefit from [espeakng-loader](https://github.com/thewh1teagle/espeakng-loader) package and do not need to install espeak-ng system wide!
If anyone still have issue with it feel free to create new issue there.
Hope it will be merged soon into phonemizer in

- https://github.com/bootphon/phonemizer/pull/191

By the way, meanwhile you can use the package `phonemizer-fork` from pypi which supported setting the espeak data path.
